[package]
name = "azul"
version = "0.1.0"
authors = ["fschutt <felix.schuett@maps4print.com>"]
edition = "2018"
build = "build.rs"
links = "azul"

[dependencies]

[[example]]
name = "bug"
path = "../examples/bug.rs"